// Fixture de référence : classeur « Plan de financement définitif optimisé - Les Violettes.xlsx ».
// Toutes les valeurs attendues des tests proviennent des cellules calculées du classeur.
import type { PlanDefinitifData } from "../planDefinitif";
import { makeAidesDefaut } from "../planDefinitif";

export function makeViolettes(): PlanDefinitifData {
  return {
    variantes: { collectif: true, collectifSansAvance: false, individuel: true },
    infos: {
      nomCopro: "La Violette",
      adresse: "213/215 route de Mittelhausbergen - 2 rue de Reitwiller - 67200 - Strasbourg",
      nbLogements: 24,
      nbLogementsEquiv: 29,
      surfaceHabitable: 1460.4,
      nbEtages: 5,
      nbEntrees: 3,
      typeChauffage: "Gaz Coll",
      cepInitial: 284,
      cepProjet: 105,
      dispositifClimaxion: true,
      etiquetteInitiale: "E",
      etiquetteProjet: "C",
    },
    lots: [
      {
        numero: 2,
        titre: "Gros oeuvre démolition",
        entreprise: "EXPERT HABITAT",
        remisePct: 0,
        lignes: [
          { designation: "Travaux préparatoires balcons", retenu: false, montantHt: 39331, tvaPct: 10 },
          { designation: "Démolition divers", retenu: false, montantHt: 6220, tvaPct: 10 },
          { designation: "Maçonnerie", retenu: false, montantHt: 3740.8, tvaPct: 10 },
        ],
      },
      {
        numero: 3,
        titre: "Façade échafaudage",
        entreprise: "ERDAL",
        remisePct: 2,
        lignes: [
          { designation: "Installation de chantier", retenu: true, montantHt: 26500, tvaPct: 10 },
          { designation: "Echafaudage", retenu: true, montantHt: 45778, tvaPct: 5.5 },
          {
            designation: "Isolation extérieure",
            groupe: "Amélioration énergétique",
            retenu: true,
            montantHt: 246353,
            tvaPct: 5.5,
          },
          { designation: "Variantes", retenu: true, montantHt: 0, tvaPct: 5.5 },
          {
            designation: "Amélioration des balcons existants",
            groupe: "Amélioration état",
            retenu: false,
            montantHt: 21172.23,
            tvaPct: 10,
          },
          { designation: "Travaux divers extérieurs", retenu: false, montantHt: 5229.04, tvaPct: 10 },
          { designation: "Travaux divers intérieurs", retenu: false, montantHt: 2009, tvaPct: 10 },
        ],
      },
      {
        numero: 4,
        titre: "Traitement de charpente",
        entreprise: "EXPERT HABITAT",
        remisePct: 0,
        lignes: [
          {
            designation: "Traitement de préservation préventif des bois de charpente existants",
            retenu: false,
            montantHt: 9485.25,
            tvaPct: 10,
          },
        ],
      },
      {
        numero: 5,
        titre: "Couverture",
        entreprise: "ATILLA",
        remisePct: 0,
        lignes: [
          { designation: "Travaux préalables", retenu: true, montantHt: 2218, tvaPct: 10 },
          { designation: "Couverture neuve", retenu: false, montantHt: 0, tvaPct: 10 },
          { designation: "Zinguerie", retenu: false, montantHt: 27157, tvaPct: 10 },
          { designation: "Désenfumage des cages d'escaliers", retenu: false, montantHt: 0, tvaPct: 10 },
          { designation: "Etanchéité terrase Bât A (Boulangerie)", retenu: true, montantHt: 17350, tvaPct: 10 },
        ],
      },
      {
        numero: 6,
        titre: "Ventilation",
        entreprise: "CAELI",
        remisePct: 0,
        lignes: [{ designation: "Ventilation hybride hygro B", retenu: true, montantHt: 68500.4, tvaPct: 5.5 }],
      },
      {
        numero: 7,
        titre: "Electricité",
        entreprise: "JS ELEC",
        remisePct: 0,
        lignes: [
          { designation: "Eclairage provisoire de chantier des combles", retenu: true, montantHt: 1332.18, tvaPct: 5.5 },
          { designation: "Consignation du réseau électrique existant", retenu: true, montantHt: 1176.75, tvaPct: 5.5 },
          { designation: "Modification de l'existant", retenu: true, montantHt: 4276.71, tvaPct: 5.5 },
        ],
      },
      {
        numero: 8,
        titre: "Menuiserie extérieure PVC et Alu",
        entreprise: "NORBA",
        remisePct: 0,
        lignes: [
          { designation: "Menuiserie extérieure PVC", retenu: true, montantHt: 89181.06, tvaPct: 5.5 },
          { designation: "Menuiserie extérieure Aluminium", retenu: true, montantHt: 14532, tvaPct: 5.5 },
          { designation: "Etanchéité", retenu: true, montantHt: 11790, tvaPct: 5.5 },
        ],
      },
      {
        numero: 9,
        titre: "Serrurerie",
        entreprise: "Heitz",
        remisePct: 0,
        lignes: [
          { designation: "Garde-corps des balcons Métal + Verre Ht 102 cm", retenu: false, montantHt: 21476.28, tvaPct: 10 },
          { designation: "Mains courantes des balcons", retenu: false, montantHt: 15643.49, tvaPct: 10 },
        ],
      },
      {
        numero: 10,
        titre: "Isolation intérieure platrerie",
        entreprise: "Expert Habitat",
        remisePct: 0,
        lignes: [
          { designation: "Isolation combles rampants", retenu: true, montantHt: 81736, tvaPct: 5.5 },
          { designation: "Doublage cage d'escaliers", retenu: true, montantHt: 5206.22, tvaPct: 5.5 },
          { designation: "Isolation plancher haut sous sol", retenu: true, montantHt: 4650.5, tvaPct: 5.5 },
        ],
      },
    ],
    moe: [
      {
        designation: "Assistance Maîtrise d'Ouvrage (phase conseil)",
        phase: "etude",
        montant: { mode: "forfait", montantHt: 2400 },
        tvaPct: 20,
        eligibleMprEtudes: false,
        eligibleMprAmo: true,
        commentaire: "Phase conseil, assistance technique projet et approche financière (Strat Eco)",
      },
      {
        designation: "Maîtrise d'œuvre phase études (DIAG- AVP)",
        phase: "etude",
        montant: { mode: "forfait", montantHt: 10300 },
        tvaPct: 10,
        eligibleMprEtudes: true,
        eligibleMprAmo: false,
        commentaire: "Etude, avant projet (M Associés)",
      },
      {
        designation: "Diagnostic amiante avant travaux",
        phase: "etude",
        montant: { mode: "forfait", montantHt: 3930 },
        tvaPct: 20,
        eligibleMprEtudes: false,
        eligibleMprAmo: false,
        commentaire: "Repérage amiante avant travaux (Devis Socotec)",
      },
      {
        designation: "Assistance Maîtrise d'Ouvrage (phase projet)",
        phase: "projet",
        montant: { mode: "forfait", montantHt: 7200 },
        tvaPct: 20,
        eligibleMprEtudes: false,
        eligibleMprAmo: true,
        commentaire: "Prestation obligatoire, assistance projet, administrative, financière (Strat Eco)",
      },
      {
        designation: "Maîtrise d'oeuvre phase conception (PRO-DCE)",
        phase: "projet",
        montant: { mode: "forfait", montantHt: 11000 },
        tvaPct: 10,
        eligibleMprEtudes: true,
        eligibleMprAmo: false,
        commentaire: "Rédaction des cahiers des charges, dépôt de PC ou DP, DCE (M Associés)",
      },
      {
        designation: "Contrôle technique",
        phase: "projet",
        montant: { mode: "forfait", montantHt: 1290 },
        tvaPct: 20,
        eligibleMprEtudes: true,
        eligibleMprAmo: false,
      },
      {
        designation: "CSPS",
        phase: "projet",
        montant: { mode: "forfait", montantHt: 320 },
        tvaPct: 20,
        eligibleMprEtudes: true,
        eligibleMprAmo: false,
      },
      {
        designation: "Test d'étanchéité à l'air avant travaux",
        phase: "projet",
        montant: { mode: "forfait", montantHt: 597 },
        tvaPct: 20,
        eligibleMprEtudes: false,
        eligibleMprAmo: false,
        commentaire: "Obligation Climaxion (Devis Ingédair)",
      },
      {
        designation: "Assistance Maîtrise d'Ouvrage (phase travaux)",
        phase: "travaux",
        montant: { mode: "forfait", montantHt: 4800 },
        tvaPct: 20,
        eligibleMprEtudes: false,
        eligibleMprAmo: true,
        commentaire: "Prestation obligatoire, assistance projet, administrative, financière (Strat Eco)",
      },
      {
        designation: "Maîtrise d'œuvre phase travaux",
        phase: "travaux",
        montant: { mode: "pctTravauxHt", taux: 5.5 },
        tvaPct: 5.5,
        eligibleMprEtudes: true,
        eligibleMprAmo: false,
        commentaire: "Pilotage et réception des travaux (M Associés)",
      },
      {
        designation: "Contrôle technique",
        phase: "travaux",
        montant: { mode: "forfait", montantHt: 3010 },
        tvaPct: 20,
        eligibleMprEtudes: true,
        eligibleMprAmo: false,
      },
      {
        designation: "CSPS",
        phase: "travaux",
        montant: { mode: "forfait", montantHt: 1680 },
        tvaPct: 20,
        eligibleMprEtudes: true,
        eligibleMprAmo: false,
      },
      {
        designation: "Test d'étanchéité à l'air après travaux",
        phase: "travaux",
        montant: { mode: "forfait", montantHt: 597 },
        tvaPct: 20,
        eligibleMprEtudes: false,
        eligibleMprAmo: false,
      },
      {
        designation: "Dommage ouvrage",
        phase: "travaux",
        montant: { mode: "pctTravauxTtc", taux: 1.9 },
        tvaPct: 0,
        eligibleMprEtudes: false,
        eligibleMprAmo: false,
        commentaire: "Obligatoire (Selon grille tarifaire Draber-Neff)",
      },
      {
        designation: "Honoraires syndic",
        phase: "travaux",
        montant: { mode: "pctTravauxHt", taux: 3.7032 },
        tvaPct: 20,
        eligibleMprEtudes: false,
        eligibleMprAmo: false,
        commentaire: "Selon informations du syndic",
      },
    ],
    aides: makeAidesDefaut(),
    params: {
      imprevusPct: 7,
      plafondTravauxParLogement: 25000,
      plafondMprParLogement: 11250,
      plafondAmoParLogement: 600,
      fondsTravaux: 5641.66,
      commentaireFondsTravaux: "Fonds travaux disponibles pour la copropriété disponible au 01/04/2026",
      totalTantiemes: 10000,
      tantiemesExemples: [310, 348, 386],
      dureeEcoPtzAns: 20,
      coefAssurance: 1.03,
      tauxPretAvancePct: 5.45,
      pctAvanceAides: 70,
    },
  };
}
